project_name: cluster-to-redpanda-migration
builds:
  - id: migration-tool-windows-and-linux
    dir: ./cluster-to-redpanda-migration/
    main: ./main.go
    binary: cluster-to-redpanda-migration
    ldflags:
      - -X github.com/redpanda-data/redpanda-operator/src/go/cluster-to-redpanda-migration/cmd/version.version={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
  - id: migration-tool-darwin
    dir: ./cluster-to-redpanda-migration/
    main: ./main.go
    binary: cluster-to-redpanda-migration
    ldflags:
      - -X github.com/redpanda-data/redpanda-operator/src/go/cluster-to-redpanda-migration/cmd/version.version={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=dist/quill-{{ .Target }}.log
archives:
  - id: migration-tool
    builds:
      - migration-tool-windows-and-linux
      - migration-tool-darwin
    format: zip
    name_template: "cluster-to-redpanda-migration-{{ .Os }}-{{ .Arch }}"
release:
  github:
    owner: redpanda-data
    name: redpanda-operator
  draft: true
  discussion_category_name: Releases
announce:
  skip: "true"
