name: Lint golang

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/go/**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'src/go/**'

jobs:
  go:
    name: Lint go files
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21.4'

    - name: Install gofumpt
      env:
        GOFUMPT_VER: 0.5.0
      run: |
        mkdir -v -p "$HOME/.local/bin"
        wget -O "$HOME/.local/bin/gofumpt" "https://github.com/mvdan/gofumpt/releases/download/v${GOFUMPT_VER}/gofumpt_v${GOFUMPT_VER}_linux_amd64"
        chmod 0700 "$HOME/.local/bin/gofumpt"

    - name: Run gofumpt
      run: |
        find src/go -type f -not -name 'zz*' -name '*.go' | xargs -n1 "$HOME/.local/bin/gofumpt" -w -lang=1.21
        git diff --exit-code

    - name: go mod tidy (cluster-to-redpanda-migration)
      working-directory: src/go/cluster-to-redpanda-migration
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum

    - name: go mod tidy (k8s)
      working-directory: src/go/k8s
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum

